# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/greet.proto\"/\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2:\n\x07Greeter\x12/\n\x08SayHello\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00\x62\x06proto3')



_MESSAGEREQUEST = DESCRIPTOR.message_types_by_name['MessageRequest']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR': _MESSAGEREQUEST,
  '__module__': 'protos.greet_pb2'
  # @@protoc_insertion_point(class_scope:MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'protos.greet_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREQUEST._serialized_start=22
  _MESSAGEREQUEST._serialized_end=69
  _MESSAGERESPONSE._serialized_start=71
  _MESSAGERESPONSE._serialized_end=105
  _GREETER._serialized_start=107
  _GREETER._serialized_end=165
# @@protoc_insertion_point(module_scope)
